name: Manage Azure Resources with Terraform

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

jobs:
  manage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: Terraform/storage_account_tf

    - name: Terraform Import Storage Account
      run: |
        terraform import azurerm_storage_account.gan_storage /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/Gan_Resource_Group/providers/Microsoft.Storage/storageAccounts/ganeshterraformdeployed || echo "Storage account already imported or not found"
      working-directory: Terraform/storage_account_tf

    - name: Terraform Import Storage Containers
      run: |
        terraform import azurerm_storage_container.container1 https://ganeshterraformdeployed.blob.core.windows.net/mycontainer1 || echo "Container mycontainer1 already imported or not found"
        terraform import azurerm_storage_container.container2 https://ganeshterraformdeployed.blob.core.windows.net/mycontainer2 || echo "Container mycontainer2 already imported or not found"
      working-directory: Terraform/storage_account_tf

    - name: Terraform Plan
      run: terraform plan
      working-directory: Terraform/storage_account_tf

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: Terraform/storage_account_tf
